<a href="https://colab.research.google.com/github/greyy004/pytorch-tutorial/blob/main/mathematic_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [4]:
t1=torch.randn(1,3)
t1


tensor([[-0.0414,  0.2733, -0.8428]])

In [28]:
t2=torch.randn(1,3)
t2

tensor([[-0.2530, -0.2558,  1.2401]])

In [9]:
t3=t1+t2
t3

tensor([[-0.0414,  0.2733, -0.8428]])

In [12]:
#Addition
torch.add(t1,t2)

tensor([[-0.0414,  0.2733, -0.8428]])

In [13]:
#Substraction
torch.sub(t1,t2)

tensor([[-0.0414,  0.2733, -0.8428]])

In [15]:
#Multiplication
torch.mul(t1,t2)

tensor([[-0., 0., -0.]])

In [17]:
#Division (The resultant is alway in float)
torch.div(t2,t1)

tensor([[-0., 0., -0.]])

In [19]:
#Modulus / Remainder
torch.remainder(t2,t1)

tensor([[0., 0., 0.]])

In [22]:
#Exponential
torch.pow(t1,t2)

tensor([[1., 1., 1.]])

In [32]:
#Reassignment (Use _ for reassignment)
t1.add_(t2)


tensor([[-1.0532, -0.7501,  4.1176]])