<a href="https://colab.research.google.com/github/greyy004/pytorch-tutorial/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [5]:
np1=np.random.rand(3,4)
np1

array([[0.02619892, 0.58737344, 0.82430878, 0.13799063],
       [0.94868509, 0.4634236 , 0.81480749, 0.0914669 ],
       [0.0653718 , 0.12911755, 0.44356597, 0.33346048]])

In [7]:
tensor_2d=torch.randn(3,4)
tensor_2d


tensor([[-0.4159,  1.0535, -0.6801,  1.4095],
        [ 1.1682, -1.0841, -2.3854,  0.6418],
        [-1.0155, -0.0722, -0.1867, -1.4285]])

In [8]:
t_3d=torch.zeros(2,3,4)
t_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
#converting numpy arrays into tensors
tensor=torch.tensor(np1)
tensor

tensor([[0.0262, 0.5874, 0.8243, 0.1380],
        [0.9487, 0.4634, 0.8148, 0.0915],
        [0.0654, 0.1291, 0.4436, 0.3335]], dtype=torch.float64)